// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Coversation() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div><a href=\"/receiver-profile\">open receiver Profile <img href=\"user.profile-picture\" alt=\"profile picture\"></a> <a href=\"/receiver-profile\" name=\"username\">username</a><p>Last time active</p><div><label for=\"message\">Search Messages</label> <input placeholder=\"search message\" name=\"message\" id=\"message\"></div></div><div><div><dialog><form hx-delete=\"/message/:messageID\"><button type=\"submit\">Delete</button></form><a>Edit Message</a></dialog></div><div><div><p>who made the massage</p><p>message sender</p><button>menu</button></div><div><p>Who made the message</p><p>message receiver</p><button>menu</button></div></div></div><div><label class=\"hidden\" for=\"message\"></label> <input id=\"message\" name=\"message\" type=\"text\"> <label for=\"image\">upload Image</label> <input id=\"image\" type=\"picture\" name=\"image\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
