// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Register() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><title>Register</title><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><script src=\"static/javascripts/htmx.min.js\"></script><link rel=\"stylesheet\" href=\"static/styles/style.css\"></head><body><form hx-post=\"/register\" hx-target=\"#response-div\" hx-indicator=\"#loading\"><div class=\"text-center text-3xl\"><h1>Register</h1></div><div><label for=\"fullname\">Your full name</label> <input id=\"fullname\" name=\"fullname\" type=\"text\" required> <label for=\"username\">Username</label> <input id=\"username\" name=\"username\" type=\"text\" required hx-post=\"/check-username\" hx-trigger=\"blur\" hx-target=\"#username-error\"><div id=\"username-error\"></div><label for=\"email\">Email</label> <input id=\"email\" name=\"email\" type=\"email\" required> <label for=\"password\">Password</label> <input id=\"password\" type=\"password\" placeholder=\"Type password\" name=\"password\" required hx-post=\"/check-password\" hx-trigger=\"blur\" hx-target=\"#password-error\"><div id=\"password-error\"></div></div><div><button type=\"submit\">Register</button></div><div id=\"loading\" class=\"htmx-indicator\">Loading...</div><div id=\"response-div\"></div><div><h2>Already have an account then Login here:</h2><a href=\"/login\">Login</a></div></form></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
